FROM python:3.9-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
COPY /data /app/data
RUN rm -rf ./data/vector_db


RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN rm -rf ./data/vector_db

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

