version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - 11434:11434/tcp
    volumes:
      - /var/opt/data/ollama/ollama:/root/.ollama
  #   # devices:
  #   #   - /dev/kfd
  #   #   - /dev/dri
    
  ai-application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-application
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data 
      - /var/opt/data/ollama/ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - PERSIST_DIR=/app/data/vector_db
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]


  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    environment:
      - TUNNEL_TOKEN=your_tunnel_token
    command: tunnel --no-autoupdate run

